version: 2.1

jobs:
  build:
    docker:
      - image: alpine:latest
    steps:
      - run:
          name: Pass or Fail?
          command: |
            ls -la
            source params.sh
            sleep $DELAY
            exit $EXIT_CODE